# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-11 14:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deneme', '0002_deneme'),
    ]

    operations = [
        migrations.CreateModel(
            name='Postumuz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=120)),
                ('content', models.TextField()),
                ('tarihi', models.DateTimeField()),
            ],
        ),
    ]
