# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-12 14:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deneme', '0004_auto_20180112_0050'),
    ]

    operations = [
        migrations.AddField(
            model_name='postumuz',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
