# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-12 19:50
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deneme', '0005_postumuz_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postumuz',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name='İçerik'),
        ),
    ]
