# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-12 22:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deneme', '0009_auto_20180113_0118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='deneme.Postumuz'),
        ),
    ]
