# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-13 16:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deneme', '0010_auto_20180113_0125'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('katadi', models.CharField(max_length=30, verbose_name='kategoriadi')),
            ],
        ),
    ]
